import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { groth16PackageRoot, groth16WorkspacePaths, resolveGroth16WorkspaceRoot } from "./paths.mjs";

const require = createRequire(import.meta.url);

const CIRCUIT_FILES = [
  ["circuits/src/templates.circom", "src/templates.circom"],
  ["circuits/src/circuit_updateTree.template.circom", "src/circuit_updateTree.template.circom"],
  ["circuits/package.json", "package.json"],
  ["circuits/package-lock.json", "package-lock.json"],
  ["circuits/run-circom-2.0.mjs", "run-circom-2.0.mjs"],
  ["circuits/circom-platform.mjs", "circom-platform.mjs"],
  ["circuits/circom-2.0-darwin-arm64", "circom-2.0-darwin-arm64"],
  ["circuits/circom-2.0-linux-amd64", "circom-2.0-linux-amd64"],
];

export async function installWorkspaceCircuit({
  workspaceRoot = resolveGroth16WorkspaceRoot(),
  metadataPath,
  metadata,
} = {}) {
  const paths = groth16WorkspacePaths(workspaceRoot);
  const resolvedMetadata = metadata ?? readJson(metadataPath ?? paths.metadataPath);

  copyCircuitPackage(paths.circuitSourceDir);
  renderCircuit({
    circuitsDir: paths.circuitSourceDir,
    mtDepth: resolvedMetadata.mtDepth,
    tokamakL2JsVersion: resolvedMetadata.tokamakL2JsVersion,
  });
  ensureCircuitDependencies(paths.circuitSourceDir);
  fs.rmSync(paths.buildDir, { recursive: true, force: true });
  run("node", [
    "./run-circom-2.0.mjs",
    "src/circuit_updateTree.circom",
    "--r1cs",
    "--wasm",
    "--sym",
    "--output",
    paths.buildDir,
    "--prime",
    "bls12381",
  ], paths.circuitSourceDir);

  const generatedWasmPath = path.join(paths.buildDir, "circuit_updateTree_js", "circuit_updateTree.wasm");
  fs.renameSync(generatedWasmPath, paths.wasmPath);
  fs.rmSync(path.join(paths.buildDir, "circuit_updateTree_js"), { recursive: true, force: true });
  fs.rmSync(path.join(paths.buildDir, "circuit_updateTree.sym"), { force: true });
  fs.rmSync(paths.circuitSourceDir, { recursive: true, force: true });

  assertFile("compiled updateTree wasm", paths.wasmPath);
  assertFile("compiled updateTree r1cs", paths.r1csPath);

  return {
    buildDir: paths.buildDir,
    wasmPath: paths.wasmPath,
    r1csPath: paths.r1csPath,
  };
}

export function renderCircuit({ circuitsDir, mtDepth, tokamakL2JsVersion }) {
  const normalizedMtDepth = Number(mtDepth);
  if (!Number.isSafeInteger(normalizedMtDepth) || normalizedMtDepth <= 0) {
    throw new Error(`Invalid Groth16 circuit MT_DEPTH: ${mtDepth}`);
  }
  const version = requireNonEmptyString(tokamakL2JsVersion, "tokamakL2JsVersion");
  const templatePath = path.join(circuitsDir, "src", "circuit_updateTree.template.circom");
  const renderedPath = path.join(circuitsDir, "src", "circuit_updateTree.circom");
  const template = fs.readFileSync(templatePath, "utf8");
  const body = template.split("__MT_DEPTH__").join(String(normalizedMtDepth));
  const rendered = [
    "pragma circom 2.2.2;",
    "",
    'include "./templates.circom";',
    "",
    "// Generated by @tokamak-private-dapps/groth16 install.",
    "// Source template: circuits/src/circuit_updateTree.template.circom",
    `// tokamak-l2js version: ${version}`,
    `// MT_DEPTH: ${normalizedMtDepth}`,
    body.split("\n").slice(3).join("\n"),
  ].join("\n");

  fs.writeFileSync(renderedPath, rendered.endsWith("\n") ? rendered : `${rendered}\n`, "utf8");
}

export function assertInstalledCircuit(workspaceRoot = resolveGroth16WorkspaceRoot()) {
  const paths = groth16WorkspacePaths(workspaceRoot);
  assertFile("compiled updateTree wasm", paths.wasmPath);
  assertFile("compiled updateTree r1cs", paths.r1csPath);
  return paths;
}

export function installedTokamakL2JsVersion() {
  const entrypoint = require.resolve("tokamak-l2js");
  const packageJsonPath = findPackageJson(path.dirname(entrypoint), "tokamak-l2js");
  return readJson(packageJsonPath).version;
}

function copyCircuitPackage(circuitsDir) {
  if (path.resolve(circuitsDir) === path.join(groth16PackageRoot, "circuits")) {
    return;
  }
  fs.rmSync(circuitsDir, { recursive: true, force: true });
  fs.mkdirSync(circuitsDir, { recursive: true });
  for (const [source, target] of CIRCUIT_FILES) {
    const sourcePath = path.join(groth16PackageRoot, source);
    const targetPath = path.join(circuitsDir, target);
    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.copyFileSync(sourcePath, targetPath);
    if (target.startsWith("circom-2.0-") || target === "run-circom-2.0.mjs") {
      fs.chmodSync(targetPath, 0o755);
    }
  }
}

function ensureCircuitDependencies(circuitsDir) {
  const poseidonCircuit = path.join(
    circuitsDir,
    "node_modules",
    "poseidon-bls12381-circom",
    "circuits",
    "poseidon255.circom",
  );
  if (fs.existsSync(poseidonCircuit)) {
    return;
  }
  run("npm", ["install", "--ignore-scripts"], circuitsDir);
}

function run(command, args, cwd) {
  execFileSync(command, args, {
    cwd,
    stdio: "inherit",
  });
}

function assertFile(label, filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing ${label}: ${filePath}`);
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function findPackageJson(startDir, packageName) {
  let current = startDir;
  while (current !== path.dirname(current)) {
    const candidate = path.join(current, "package.json");
    if (fs.existsSync(candidate) && readJson(candidate).name === packageName) {
      return candidate;
    }
    current = path.dirname(current);
  }
  throw new Error(`Cannot locate ${packageName} package.json above ${startDir}.`);
}

function requireNonEmptyString(value, label) {
  const normalized = String(value ?? "").trim();
  if (!normalized) {
    throw new Error(`${label} must be a non-empty string.`);
  }
  return normalized;
}
