[profile.default]
src = "."
test = "test"
out = "out"
libs = ["../lib"]
remappings = [
    "forge-std/=../lib/forge-std/src/",
]

optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "prague"
fs_permissions = [
    { access = "read", path = "./test/fixtures" },
    { access = "read", path = "../submodules/Tokamak-zk-EVM/dist/resource/qap-compiler/library/setupParams.json" },
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
