pragma circom 2.2.2;

include "./templates.circom";

// Generated by packages/groth16/mpc-setup/generate_update_tree_setup_from_dusk.mjs.
// Source template: packages/groth16/circuits/src/circuit_updateTree.template.circom
// tokamak-l2js version: 0.1.3
// MT_DEPTH: 30

// This entrypoint is rendered by the updateTree trusted-setup generator.
// The generator injects the locally installed tokamak-l2js MT_DEPTH into the updateTree depth parameter.
component main{public [root_before, root_after, storage_key, storage_value_before, storage_value_after]} = updateTree(30);
