pragma circom 2.2.2;

include "./templates.circom";

// Generated by @tokamak-private-dapps/groth16 install.
// Source template: circuits/src/circuit_updateTree.template.circom
// tokamak-l2js version: 0.1.3
// MT_DEPTH: 30

// This entrypoint is rendered by the updateTree trusted-setup generator.
// The generator injects the latest tokamak-l2js MT_DEPTH into the updateTree depth parameter.
component main{public [root_before, root_after, storage_key, storage_value_before, storage_value_after]} = updateTree(30);
